config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sales#table'

  resources :sales, only: [:index] do
    collection do
      get :refresh
      get :table
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :sales

  validates :title, presence: true

  def revenue(start_date, end_date)
    sum_revenue = 0
    sales.where(date: start_date..end_date).each do |sale|
      sum_revenue += sale.revenue
    end
    return sum_revenue
  end
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :good

  validates :date, :revenue, :good, presence: true

  def self.total_revenue(start_date, end_date)
    sum_revenue = 0
    where(date: start_date..end_date).each do |sale|
      sum_revenue += sale.revenue
    end
    return sum_revenue
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_action :set_goods
  before_action :sales_params, only: [:index, :refresh]
  before_action :set_json_response_format, only: [:index]

  def index
  end

  def table
    @default_date = Date.new(2017, 03, 01)
  end

  def refresh
  end

  private

  def set_goods
    @goods = Good.all
  end

  def sales_params
    if params.has_key?(:from) && params.has_key?(:to)
      @start_date = params[:from]
      @end_date = params[:to]
    else
      render json: { error: 'You must set start and end dates!' }, status: 422
    end
  end

  def set_json_response_format
    request.format = :json
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roonyx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_table.html.slim
#sales
  table.table
    tr
      td Good
      td = "#{start_date} - #{end_date}"
    - goods.each do |good|
      tr
        td = good.title
        td = good.revenue(start_date, end_date)

app/views/sales/refresh.js.erb
$('#sales').replaceWith("<%= j render 'table', goods: @goods, start_date: @start_date, end_date: @end_date, dates: @dates %>");

app/views/sales/table.html.slim
#page-container
  .logo REVENUE
  = form_with url: refresh_sales_path, method: :get, class: 'total-revenue form-inline' do |form|
    = form.label :from, 'From', class: 'mb-2 mr-sm-2'
    = form.date_field :from, class: 'form-control mb-2 mr-sm-2'

    = form.label :to, 'To', class: 'mb-2 mr-sm-2'
    = form.date_field :to, class: 'form-control mb-2 mr-sm-2'

    = form.submit 'Refresh', class: 'btn btn-primary mb-2 mr-sm-2'

  = render 'table', goods: @goods, start_date: @default_date, end_date: @default_date